common: Remove probably superfluous import
The purpose of this import is unclear.

This import caused the following error with Sphinx 3.0:

Extension error:
Could not import extension rtemsdomain (exception: cannot import name 'l_')